services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chariot
      PGHOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
    # Including for ease of running
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chariot
    ports:
    # Exposing locally for testing convenience
      - "5432:5432"
    volumes:
    - ./migrations:/migrations
    - ./docker/postgres:/script/
    entrypoint: ["/script/init.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5